services:
  pgdatabase:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=emlak
    volumes:
      - "~/docker_data_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase # metabase should be created before..
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: 123
      MB_DB_HOST: pgdatabase
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
        - pgdatabase
    volumes:
      - "~/docker_data_metabase:/metabase-data:rw"
    ports:
      - 3000:3000
